# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_norm.ui'
#
# Created: Thu Dec  4 16:22:02 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Norm(object):
    def setupUi(self, Norm):
        Norm.setObjectName(_fromUtf8("Norm"))
        Norm.resize(467, 424)
        Norm.setMinimumSize(QtCore.QSize(467, 365))
        Norm.setMaximumSize(QtCore.QSize(467, 465))
        Norm.setInputMethodHints(QtCore.Qt.ImhNone)
        self.normcomboBox = QtGui.QComboBox(Norm)
        self.normcomboBox.setGeometry(QtCore.QRect(40, 150, 171, 27))
        self.normcomboBox.setObjectName(_fromUtf8("normcomboBox"))
        self.normcomboBox.addItem(_fromUtf8(""))
        self.normcomboBox.addItem(_fromUtf8(""))
        self.normcomboBox.addItem(_fromUtf8(""))
        self.normcomboBox.addItem(_fromUtf8(""))
        self.normcomboBox.addItem(_fromUtf8(""))
        self.titleLabel = QtGui.QLabel(Norm)
        self.titleLabel.setGeometry(QtCore.QRect(160, 20, 141, 31))
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.normlabel = QtGui.QLabel(Norm)
        self.normlabel.setGeometry(QtCore.QRect(50, 115, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.normlabel.setFont(font)
        self.normlabel.setObjectName(_fromUtf8("normlabel"))
        self.layerlabel = QtGui.QLabel(Norm)
        self.layerlabel.setGeometry(QtCore.QRect(50, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.layerlabel.setFont(font)
        self.layerlabel.setObjectName(_fromUtf8("layerlabel"))
        self.layercomboBox = QtGui.QComboBox(Norm)
        self.layercomboBox.setEnabled(True)
        self.layercomboBox.setGeometry(QtCore.QRect(50, 80, 361, 27))
        self.layercomboBox.setObjectName(_fromUtf8("layercomboBox"))
        self.OKButton = QtGui.QPushButton(Norm)
        self.OKButton.setGeometry(QtCore.QRect(330, 380, 98, 27))
        self.OKButton.setObjectName(_fromUtf8("OKButton"))
        self.CancelButton = QtGui.QPushButton(Norm)
        self.CancelButton.setGeometry(QtCore.QRect(220, 380, 98, 27))
        self.CancelButton.setObjectName(_fromUtf8("CancelButton"))
        self.minmaxframe = QtGui.QFrame(Norm)
        self.minmaxframe.setGeometry(QtCore.QRect(40, 200, 171, 101))
        self.minmaxframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.minmaxframe.setFrameShadow(QtGui.QFrame.Raised)
        self.minmaxframe.setObjectName(_fromUtf8("minmaxframe"))
        self.LHlabel = QtGui.QLabel(self.minmaxframe)
        self.LHlabel.setGeometry(QtCore.QRect(30, 4, 108, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.LHlabel.setFont(font)
        self.LHlabel.setObjectName(_fromUtf8("LHlabel"))
        self.PLOW = QtGui.QLabel(self.minmaxframe)
        self.PLOW.setEnabled(True)
        self.PLOW.setGeometry(QtCore.QRect(10, 30, 31, 21))
        self.PLOW.setObjectName(_fromUtf8("PLOW"))
        self.lineEditNL = QtGui.QLineEdit(self.minmaxframe)
        self.lineEditNL.setEnabled(True)
        self.lineEditNL.setGeometry(QtCore.QRect(70, 30, 81, 27))
        self.lineEditNL.setObjectName(_fromUtf8("lineEditNL"))
        self.PHIGH = QtGui.QLabel(self.minmaxframe)
        self.PHIGH.setEnabled(True)
        self.PHIGH.setGeometry(QtCore.QRect(10, 60, 36, 17))
        self.PHIGH.setObjectName(_fromUtf8("PHIGH"))
        self.lineEditNH = QtGui.QLineEdit(self.minmaxframe)
        self.lineEditNH.setEnabled(True)
        self.lineEditNH.setGeometry(QtCore.QRect(70, 60, 81, 27))
        self.lineEditNH.setObjectName(_fromUtf8("lineEditNH"))
        self.tableWidget = QtGui.QTableWidget(Norm)
        self.tableWidget.setGeometry(QtCore.QRect(250, 150, 171, 151))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(171, 16777215))
        self.tableWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(9, 1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(63)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(63)
        self.lineEdit_outputpath = QtGui.QLineEdit(Norm)
        self.lineEdit_outputpath.setGeometry(QtCore.QRect(40, 320, 311, 27))
        self.lineEdit_outputpath.setObjectName(_fromUtf8("lineEdit_outputpath"))
        self.Button_path = QtGui.QPushButton(Norm)
        self.Button_path.setGeometry(QtCore.QRect(360, 320, 61, 27))
        self.Button_path.setObjectName(_fromUtf8("Button_path"))
        self.checkBox = QtGui.QCheckBox(Norm)
        self.checkBox.setGeometry(QtCore.QRect(40, 350, 131, 22))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.logolabel = QtGui.QLabel(Norm)
        self.logolabel.setGeometry(QtCore.QRect(350, 10, 101, 21))
        self.logolabel.setText(_fromUtf8(""))
        self.logolabel.setPixmap(QtGui.QPixmap(_fromUtf8("sensum.png")))
        self.logolabel.setObjectName(_fromUtf8("logolabel"))
        self.helpButton = QtGui.QPushButton(Norm)
        self.helpButton.setGeometry(QtCore.QRect(30, 380, 98, 27))
        self.helpButton.setObjectName(_fromUtf8("helpButton"))

        self.retranslateUi(Norm)
        QtCore.QMetaObject.connectSlotsByName(Norm)

    def retranslateUi(self, Norm):
        Norm.setWindowTitle(_translate("Norm", "Normalization", None))
        self.normcomboBox.setItemText(0, _translate("Norm", "MIN_MAX", None))
        self.normcomboBox.setItemText(1, _translate("Norm", "LOGARITHMIC", None))
        self.normcomboBox.setItemText(2, _translate("Norm", "QUADRATIC", None))
        self.normcomboBox.setItemText(3, _translate("Norm", "INV-LOGIT", None))
        self.normcomboBox.setItemText(4, _translate("Norm", "LOG-SQUARE", None))
        self.titleLabel.setText(_translate("Norm", "<html><head/><body><p><span style=\" font-size:16pt;\">Normalization </span></p></body></html>", None))
        self.normlabel.setText(_translate("Norm", "Norm Methods:", None))
        self.layerlabel.setText(_translate("Norm", "Raster Layer:", None))
        self.OKButton.setText(_translate("Norm", "OK", None))
        self.CancelButton.setText(_translate("Norm", "Cancel", None))
        self.LHlabel.setText(_translate("Norm", "Rejection Bound", None))
        self.PLOW.setText(_translate("Norm", "LOW", None))
        self.PHIGH.setText(_translate("Norm", "HIGH", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Norm", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Norm", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Norm", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Norm", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Norm", "5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Norm", "6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Norm", "7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Norm", "8", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Norm", "9", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Norm", "10", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Norm", "X", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Norm", "Y", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.Button_path.setText(_translate("Norm", "...", None))
        self.checkBox.setText(_translate("Norm", "Add to Canvas", None))
        self.helpButton.setText(_translate("Norm", "Help", None))

